### ISSUE TITLE
Separate functions into own modules

### ISSUE THREAD

**Issue by camvr** [camvr/Thorold#1]
Move functions into their own files so that it's not all just loaded into the main kernel file.

**Comment by tonyxmella66** [comment]
Will do

**Comment by camvr** [comment]
NO PLZ IM NEARLY DONE!!11!!11

**Comment by tonyxmella66** [comment]
wot m8?

**Comment by camvr** [comment]
Finished TODO. See commit 82400573e26b1727c48348ea8acd94ce26144985
